hugoblox:
  schema: "2.0"
  identity:
    name: Hiroto Aoki
    type: person
    tagline: Human Augmentation Researcher
    description: ""
  theme:
    mode: system
    pack: dracula
    colors:
      primary: fuchsia
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: rounded
  header:
    enable: true
    style: navbar
    sticky: true
    align: right
    search: false
    theme_toggle: true
    language_switcher: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
